api-gateway:
  host: api_gateway
  port: 9000

token:
  key: 6oyimtihon

file:
  cert: ./tls/cert.pem
  key: ./tls/key.pem

services:
  user-service:
    host: user_service
    port: 8001
  incexp-service:
    host: incexp_service
    port: 8002
  reporting-service:
    host: reporting_service
    port: 8003
  budget-service:
    host: budget_service
    port: 8004
  