// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package storage

import (
	"database/sql"

	"github.com/google/uuid"
)

type Budget struct {
	ID        uuid.UUID
	Category  string
	Amount    float64
	Spent     sql.NullFloat64
	Currency  string
	CreatedAt sql.NullString
	UpdatedAt sql.NullString
	DeletedAt sql.NullInt32
}
