// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package storage

import (
	"database/sql"

	"github.com/google/uuid"
)

type User struct {
	ID        uuid.UUID
	Username  string
	Password  string
	Email     string
	CreatedAt sql.NullString
	UpdatedAt sql.NullString
	DeletedAt sql.NullInt32
}
