service:
  host: localhost
  port: 8001

postgres:
  host: localhost
  port: 5432
  dbname: usersdb
  username: postgres
  password: 1

redis:
  host: localhost
  port: 6379

email: bekzodnematov709@gmail.com
accessKey: funt snwb bqdo kqfk

auth:
  secretKey: 6oyimtihon