// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: protos/budget-service/budget.proto

package budgetpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Budget struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Category string     `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Amount   float32    `protobuf:"fixed32,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Spent    float32    `protobuf:"fixed32,4,opt,name=spent,proto3" json:"spent,omitempty"`
	Currency string     `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Cud      *CUDBudget `protobuf:"bytes,6,opt,name=cud,proto3" json:"cud,omitempty"`
}

func (x *Budget) Reset() {
	*x = Budget{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_budget_service_budget_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Budget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Budget) ProtoMessage() {}

func (x *Budget) ProtoReflect() protoreflect.Message {
	mi := &file_protos_budget_service_budget_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Budget.ProtoReflect.Descriptor instead.
func (*Budget) Descriptor() ([]byte, []int) {
	return file_protos_budget_service_budget_proto_rawDescGZIP(), []int{0}
}

func (x *Budget) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Budget) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Budget) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Budget) GetSpent() float32 {
	if x != nil {
		return x.Spent
	}
	return 0
}

func (x *Budget) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Budget) GetCud() *CUDBudget {
	if x != nil {
		return x.Cud
	}
	return nil
}

type CUDBudget struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreatedAt string `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt string `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt int64  `protobuf:"varint,3,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
}

func (x *CUDBudget) Reset() {
	*x = CUDBudget{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_budget_service_budget_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CUDBudget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CUDBudget) ProtoMessage() {}

func (x *CUDBudget) ProtoReflect() protoreflect.Message {
	mi := &file_protos_budget_service_budget_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CUDBudget.ProtoReflect.Descriptor instead.
func (*CUDBudget) Descriptor() ([]byte, []int) {
	return file_protos_budget_service_budget_proto_rawDescGZIP(), []int{1}
}

func (x *CUDBudget) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CUDBudget) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *CUDBudget) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

// Create Budget
type CreateBudgetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category string  `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Amount   float32 `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency string  `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
}

func (x *CreateBudgetReq) Reset() {
	*x = CreateBudgetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_budget_service_budget_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBudgetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBudgetReq) ProtoMessage() {}

func (x *CreateBudgetReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_budget_service_budget_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBudgetReq.ProtoReflect.Descriptor instead.
func (*CreateBudgetReq) Descriptor() ([]byte, []int) {
	return file_protos_budget_service_budget_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBudgetReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateBudgetReq) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateBudgetReq) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type CreateBudgetResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  bool    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message string  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Budget  *Budget `protobuf:"bytes,3,opt,name=budget,proto3" json:"budget,omitempty"`
}

func (x *CreateBudgetResp) Reset() {
	*x = CreateBudgetResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_budget_service_budget_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBudgetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBudgetResp) ProtoMessage() {}

func (x *CreateBudgetResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_budget_service_budget_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBudgetResp.ProtoReflect.Descriptor instead.
func (*CreateBudgetResp) Descriptor() ([]byte, []int) {
	return file_protos_budget_service_budget_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBudgetResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *CreateBudgetResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateBudgetResp) GetBudget() *Budget {
	if x != nil {
		return x.Budget
	}
	return nil
}

// Update Budget
type UpdateBudgetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Category string  `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Amount   float32 `protobuf:"fixed32,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency string  `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
}

func (x *UpdateBudgetReq) Reset() {
	*x = UpdateBudgetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_budget_service_budget_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBudgetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBudgetReq) ProtoMessage() {}

func (x *UpdateBudgetReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_budget_service_budget_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBudgetReq.ProtoReflect.Descriptor instead.
func (*UpdateBudgetReq) Descriptor() ([]byte, []int) {
	return file_protos_budget_service_budget_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateBudgetReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateBudgetReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UpdateBudgetReq) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UpdateBudgetReq) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type UpdateBudgetResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  bool    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message string  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Budget  *Budget `protobuf:"bytes,3,opt,name=budget,proto3" json:"budget,omitempty"`
}

func (x *UpdateBudgetResp) Reset() {
	*x = UpdateBudgetResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_budget_service_budget_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBudgetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBudgetResp) ProtoMessage() {}

func (x *UpdateBudgetResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_budget_service_budget_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBudgetResp.ProtoReflect.Descriptor instead.
func (*UpdateBudgetResp) Descriptor() ([]byte, []int) {
	return file_protos_budget_service_budget_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateBudgetResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *UpdateBudgetResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateBudgetResp) GetBudget() *Budget {
	if x != nil {
		return x.Budget
	}
	return nil
}

// Delete Budget
type DeleteBudgetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteBudgetReq) Reset() {
	*x = DeleteBudgetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_budget_service_budget_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBudgetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBudgetReq) ProtoMessage() {}

func (x *DeleteBudgetReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_budget_service_budget_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBudgetReq.ProtoReflect.Descriptor instead.
func (*DeleteBudgetReq) Descriptor() ([]byte, []int) {
	return file_protos_budget_service_budget_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteBudgetReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteBudgetResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  bool   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeleteBudgetResp) Reset() {
	*x = DeleteBudgetResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_budget_service_budget_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBudgetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBudgetResp) ProtoMessage() {}

func (x *DeleteBudgetResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_budget_service_budget_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBudgetResp.ProtoReflect.Descriptor instead.
func (*DeleteBudgetResp) Descriptor() ([]byte, []int) {
	return file_protos_budget_service_budget_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteBudgetResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *DeleteBudgetResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Get Budget By Id
type GetBudgetByIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetBudgetByIdReq) Reset() {
	*x = GetBudgetByIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_budget_service_budget_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBudgetByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBudgetByIdReq) ProtoMessage() {}

func (x *GetBudgetByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_budget_service_budget_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBudgetByIdReq.ProtoReflect.Descriptor instead.
func (*GetBudgetByIdReq) Descriptor() ([]byte, []int) {
	return file_protos_budget_service_budget_proto_rawDescGZIP(), []int{8}
}

func (x *GetBudgetByIdReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetBudgetByIdResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  bool    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message string  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Budget  *Budget `protobuf:"bytes,3,opt,name=budget,proto3" json:"budget,omitempty"`
}

func (x *GetBudgetByIdResp) Reset() {
	*x = GetBudgetByIdResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_budget_service_budget_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBudgetByIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBudgetByIdResp) ProtoMessage() {}

func (x *GetBudgetByIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_budget_service_budget_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBudgetByIdResp.ProtoReflect.Descriptor instead.
func (*GetBudgetByIdResp) Descriptor() ([]byte, []int) {
	return file_protos_budget_service_budget_proto_rawDescGZIP(), []int{9}
}

func (x *GetBudgetByIdResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *GetBudgetByIdResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetBudgetByIdResp) GetBudget() *Budget {
	if x != nil {
		return x.Budget
	}
	return nil
}

// Get Budgets
type GetBudgetsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetBudgetsReq) Reset() {
	*x = GetBudgetsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_budget_service_budget_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBudgetsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBudgetsReq) ProtoMessage() {}

func (x *GetBudgetsReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_budget_service_budget_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBudgetsReq.ProtoReflect.Descriptor instead.
func (*GetBudgetsReq) Descriptor() ([]byte, []int) {
	return file_protos_budget_service_budget_proto_rawDescGZIP(), []int{10}
}

type GetBudgetsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  bool      `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message string    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Count   int64     `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Budget  []*Budget `protobuf:"bytes,4,rep,name=budget,proto3" json:"budget,omitempty"`
}

func (x *GetBudgetsResp) Reset() {
	*x = GetBudgetsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_budget_service_budget_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBudgetsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBudgetsResp) ProtoMessage() {}

func (x *GetBudgetsResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_budget_service_budget_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBudgetsResp.ProtoReflect.Descriptor instead.
func (*GetBudgetsResp) Descriptor() ([]byte, []int) {
	return file_protos_budget_service_budget_proto_rawDescGZIP(), []int{11}
}

func (x *GetBudgetsResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *GetBudgetsResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetBudgetsResp) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetBudgetsResp) GetBudget() []*Budget {
	if x != nil {
		return x.Budget
	}
	return nil
}

var File_protos_budget_service_budget_proto protoreflect.FileDescriptor

var file_protos_budget_service_budget_proto_rawDesc = []byte{
	0x0a, 0x22, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x2d,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9c, 0x01, 0x0a, 0x06, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x05, 0x73, 0x70, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x1c, 0x0a, 0x03, 0x63, 0x75, 0x64, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x43, 0x55, 0x44, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x52, 0x03,
	0x63, 0x75, 0x64, 0x22, 0x68, 0x0a, 0x09, 0x43, 0x55, 0x44, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x61, 0x0a,
	0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79,
	0x22, 0x65, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x62, 0x75, 0x64, 0x67, 0x65, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x52,
	0x06, 0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x22, 0x71, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x22, 0x65, 0x0a, 0x10, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x1f, 0x0a, 0x06, 0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x07, 0x2e, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x52, 0x06, 0x62, 0x75, 0x64, 0x67, 0x65,
	0x74, 0x22, 0x21, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x75, 0x64, 0x67, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x44, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x75,
	0x64, 0x67, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x22, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x66,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x52, 0x06,
	0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x42, 0x75, 0x64,
	0x67, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x22, 0x79, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x42, 0x75,
	0x64, 0x67, 0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x1f, 0x0a, 0x06, 0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x07, 0x2e, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x52, 0x06, 0x62, 0x75, 0x64, 0x67,
	0x65, 0x74, 0x32, 0x9f, 0x02, 0x0a, 0x0d, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x35, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75,
	0x64, 0x67, 0x65, 0x74, 0x12, 0x10, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x64,
	0x67, 0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42,
	0x75, 0x64, 0x67, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x0c, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x12, 0x10, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x00, 0x12, 0x35, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x75, 0x64, 0x67,
	0x65, 0x74, 0x12, 0x10, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x75, 0x64, 0x67, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x75, 0x64,
	0x67, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x0d, 0x47, 0x65, 0x74,
	0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x11, 0x2e, 0x47, 0x65, 0x74,
	0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e,
	0x47, 0x65, 0x74, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x12, 0x2f, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74,
	0x73, 0x12, 0x0e, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x73, 0x52, 0x65,
	0x71, 0x1a, 0x0f, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x00, 0x42, 0x13, 0x5a, 0x11, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_protos_budget_service_budget_proto_rawDescOnce sync.Once
	file_protos_budget_service_budget_proto_rawDescData = file_protos_budget_service_budget_proto_rawDesc
)

func file_protos_budget_service_budget_proto_rawDescGZIP() []byte {
	file_protos_budget_service_budget_proto_rawDescOnce.Do(func() {
		file_protos_budget_service_budget_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_budget_service_budget_proto_rawDescData)
	})
	return file_protos_budget_service_budget_proto_rawDescData
}

var file_protos_budget_service_budget_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_protos_budget_service_budget_proto_goTypes = []any{
	(*Budget)(nil),            // 0: Budget
	(*CUDBudget)(nil),         // 1: CUDBudget
	(*CreateBudgetReq)(nil),   // 2: CreateBudgetReq
	(*CreateBudgetResp)(nil),  // 3: CreateBudgetResp
	(*UpdateBudgetReq)(nil),   // 4: UpdateBudgetReq
	(*UpdateBudgetResp)(nil),  // 5: UpdateBudgetResp
	(*DeleteBudgetReq)(nil),   // 6: DeleteBudgetReq
	(*DeleteBudgetResp)(nil),  // 7: DeleteBudgetResp
	(*GetBudgetByIdReq)(nil),  // 8: GetBudgetByIdReq
	(*GetBudgetByIdResp)(nil), // 9: GetBudgetByIdResp
	(*GetBudgetsReq)(nil),     // 10: GetBudgetsReq
	(*GetBudgetsResp)(nil),    // 11: GetBudgetsResp
}
var file_protos_budget_service_budget_proto_depIdxs = []int32{
	1,  // 0: Budget.cud:type_name -> CUDBudget
	0,  // 1: CreateBudgetResp.budget:type_name -> Budget
	0,  // 2: UpdateBudgetResp.budget:type_name -> Budget
	0,  // 3: GetBudgetByIdResp.budget:type_name -> Budget
	0,  // 4: GetBudgetsResp.budget:type_name -> Budget
	2,  // 5: BudgetService.CreateBudget:input_type -> CreateBudgetReq
	4,  // 6: BudgetService.UpdateBudget:input_type -> UpdateBudgetReq
	6,  // 7: BudgetService.DeleteBudget:input_type -> DeleteBudgetReq
	8,  // 8: BudgetService.GetBudgetById:input_type -> GetBudgetByIdReq
	10, // 9: BudgetService.GetBudgets:input_type -> GetBudgetsReq
	3,  // 10: BudgetService.CreateBudget:output_type -> CreateBudgetResp
	5,  // 11: BudgetService.UpdateBudget:output_type -> UpdateBudgetResp
	7,  // 12: BudgetService.DeleteBudget:output_type -> DeleteBudgetResp
	9,  // 13: BudgetService.GetBudgetById:output_type -> GetBudgetByIdResp
	11, // 14: BudgetService.GetBudgets:output_type -> GetBudgetsResp
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_protos_budget_service_budget_proto_init() }
func file_protos_budget_service_budget_proto_init() {
	if File_protos_budget_service_budget_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_budget_service_budget_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Budget); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_budget_service_budget_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CUDBudget); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_budget_service_budget_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CreateBudgetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_budget_service_budget_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CreateBudgetResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_budget_service_budget_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateBudgetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_budget_service_budget_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateBudgetResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_budget_service_budget_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteBudgetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_budget_service_budget_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteBudgetResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_budget_service_budget_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*GetBudgetByIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_budget_service_budget_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*GetBudgetByIdResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_budget_service_budget_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*GetBudgetsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_budget_service_budget_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*GetBudgetsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_budget_service_budget_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_budget_service_budget_proto_goTypes,
		DependencyIndexes: file_protos_budget_service_budget_proto_depIdxs,
		MessageInfos:      file_protos_budget_service_budget_proto_msgTypes,
	}.Build()
	File_protos_budget_service_budget_proto = out.File
	file_protos_budget_service_budget_proto_rawDesc = nil
	file_protos_budget_service_budget_proto_goTypes = nil
	file_protos_budget_service_budget_proto_depIdxs = nil
}
