service:
  host: user_service
  port: 8001

postgres:
  host: postgres
  port: 5432
  dbname: usersdb
  username: postgres
  password: 1

redis:
  host: redis
  port: 6379

email: bekzodnematov709@gmail.com
accessKey: funt snwb bqdo kqfk

auth:
  secretKey: 6oyimtihon